// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFG820Hie-CA5kr_V2eTUT_UUd0k8liHU',
    appId: '1:376235707920:web:c8a04cfebe827f2bff0495',
    messagingSenderId: '376235707920',
    projectId: 'space-words-2c8cd',
    authDomain: 'space-words-2c8cd.firebaseapp.com',
    storageBucket: 'space-words-2c8cd.firebasestorage.app',
    measurementId: 'G-1SPHLE0SPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYkX2fHUapPUXqnpcSGe0dKsL_BvdYaM',
    appId: '1:376235707920:android:ca7992e7382490b4ff0495',
    messagingSenderId: '376235707920',
    projectId: 'space-words-2c8cd',
    storageBucket: 'space-words-2c8cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGKOjehjb-jQu4z2WVkoZ28r1aAPCsGqM',
    appId: '1:376235707920:ios:64e88fc7fd2d8633ff0495',
    messagingSenderId: '376235707920',
    projectId: 'space-words-2c8cd',
    storageBucket: 'space-words-2c8cd.firebasestorage.app',
    iosBundleId: 'com.yourwebsite.grammarGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGKOjehjb-jQu4z2WVkoZ28r1aAPCsGqM',
    appId: '1:376235707920:ios:64e88fc7fd2d8633ff0495',
    messagingSenderId: '376235707920',
    projectId: 'space-words-2c8cd',
    storageBucket: 'space-words-2c8cd.firebasestorage.app',
    iosBundleId: 'com.yourwebsite.grammarGame',
  );
}
